version: "3.8"
networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-docker-certs:
  jenkins-data:

services:
  jenkins-docker:
    image: docker:dind
    networks:
      - jenkins
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    environment:
      - DOCKER_TLS_CERTDIR=/certs
  jenkins-blueocean:
    image: esdp-jenkins-blueocean:1.1
    build:
      context: .
    networks:
      - jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-docker-certs:/certs/client:ro
      - jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_HOST=tcp://docker:2376
    depends_on:
      - "jenkins-docker"
